initial push for question 2
NSS-Full-Time-Data-Analytics-8/lahman_baseball-nerds pull request #2
Opened 2022-10-04 19:51 UTC by officialbubies

I have no idea what im doing!

2022-10-04 20:00 UTC, Kytsuine commented
On the first query, I'd add a LIMIT 1 to avoid cluttering your output; you only need the shortest person. Also, I'm not sure the MIN() is necessary, since there's only one height per row.

On the second, I'm pretty sure the answer is supposed to be one (as per Wikipedia); is it possible that 52 is the number of games the Browns played that year?

2022-10-04 20:31 UTC, Kytsuine requested changes
See comment on Conversation tab.

2022-10-04 20:35 UTC, Kytsuine approved these changes

2022-10-05 15:57 UTC, Lewis-Garvin approved these changes
Looks good. In first query, don' t need to do group by, but current approach works.

2022-10-05 16:03 UTC, merged